# Generated by Django 5.2.5 on 2025-08-12 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=200, verbose_name='ФИО')),
                ('flight_number', models.CharField(blank=True, max_length=10, verbose_name='Рейс')),
                ('departure_city', models.CharField(blank=True, max_length=100, verbose_name='Город вылета')),
                ('arrival_city', models.CharField(blank=True, max_length=100, verbose_name='Город прилёта')),
                ('departure_date', models.CharField(blank=True, max_length=20, verbose_name='Дата вылета')),
                ('departure_time', models.CharField(blank=True, max_length=10, verbose_name='Время вылета')),
                ('seat', models.CharField(blank=True, max_length=10, verbose_name='Место')),
                ('ticket_class', models.CharField(blank=True, max_length=20, verbose_name='Класс')),
                ('document_type', models.CharField(max_length=10, verbose_name='Тип документа')),
                ('uploaded_file', models.FileField(upload_to='tickets/', verbose_name='Файл')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Билет',
                'verbose_name_plural': 'Билеты',
            },
        ),
    ]
