# Generated by Django 5.2.5 on 2025-08-12 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_ticket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='uploaded_file',
            field=models.FileField(upload_to='parser_ticket/', verbose_name='Файл'),
        ),
    ]
