# Generated by Django 5.2.5 on 2025-08-12 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_ticket', '0002_alter_ticket_uploaded_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='extracted_text',
            field=models.TextField(blank=True, verbose_name='Извлеченный текст'),
        ),
    ]
